remote_theme: "mmistakes/minimal-mistakes@4.21.0"
plugins:
  - jekyll-include-cache
  - jekyll-titles-from-headings

# Site Settings
locale                   : "en-US"
title                    : "DuinoDCX"
title_separator          : "-"
subtitle                 : "WiFi remote controller for the Behringer Ultradrive."
name                     : "Lasse Lukkari"
description              : "DuinoDCX User Guide."
repository               : "lasselukkari/DuinoDCX"

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
